name: Go CI

on:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ci-go-${{ github.ref }}
  cancel-in-progress: true

jobs:
  go:
    name: Go
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: false
      - run: go test ./...
